---
- name: Install database, webserver and PHP
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - mysql-server
    - mysql-client
    - apache2
    - apache2.2-common
    - apache2-mpm-prefork
    - apache2-utils
    - libexpat1
    - ssl-cert
    - libapache2-mod-wsgi
    - php5
    - libapache2-mod-php5
    - python-mysqldb
  notify: restart apache

- name: Set ServerName
  lineinfile: path=/etc/apache2/conf.d/name line='ServerName localhost' create=yes
  notify: restart apache
